type User {
  id: ID!
  displayName: String!
  email: String!
  password: String!
  active: Boolean
  role: RolesEnum
  validated: Boolean
}

type Query {
  users: [User!]!
  user(id: ID!): User!
  me: User!
}

input UserCreateInput {
  displayName: String!
  email: String!
  password: String!
}

input UserUpdateInput {
  id: ID!
  displayName: String
  email: String
  password: String
}

type AuthPayload {
  user: User!
}

type Mutation {
  signup(data: UserCreateInput!): User!
  login(email: String!, password: String!): AuthPayload!
  logout: Boolean
  createUser(data: UserCreateInput!): User!
  updateUser(data: UserUpdateInput!): Boolean
  deleteUser(id: ID!): Boolean
}
